include tokyo-night-kitty.conf

# Font
font_family         JetBrainsMono NF
italic_font         auto
bold_font           auto
bold_italic_font    auto
font_size           12.0

# Remove Bell!
enable_audio_bell   no

# Tab Bar
tab_bar_edge        top
tab_bar_align       left
tab_bar_style       fade

# Clipboard
map ctrl+shift+c    copy_to_clipboard
map ctrl+shift+v    paste_from_clipboard
map ctrl+shift+s    paste_from_selection

# Scrolling
map ctrl+shift+up   scroll_line_up
map ctrl+shift+k    scroll_line_up
map ctrl+shift+down scroll_line_down
map ctrl+shift+j    scroll_line_down
map ctrl+shift+page_up scroll_page_up
map ctrl+shift+page_down scroll_page_down
map ctrl+shift+home scroll_home
map ctrl+shift+end scroll_end
map ctrl+shift+z scroll_to_prompt -1
map ctrl+shift+x scroll_to_prompt 1
