# Theme
import = [
    "~/.config/alacritty/tokyo-night.toml"
]
live_config_reload = true

[window]
padding = {x=0, y=0}
decorations = "Full"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
size = 12
# Value not specified for bold, italic, etc. as it will fall back to normal value
